from . import sales_rep
from . import visit
from . import collection
from . import dashboard
from . import inherited_models
from . import sales_rep_report
from . import contact
from . import res_config_settings
from . import hr_employee
from . import payment_method
from . import return_reason
from . import visit_types
from . import stock_quant
from . import product_product
from . import sync_triggers
