{'name': 'POS Access Management (User + Employee)',
 'version': '18.0.3.0.0',
 'sequence': 5,
 'author': 'Terabits Technolab',
 'license': 'OPL-1',
 'category': 'Services',
 'website': '',
 'description': '\n'
                '        All In One POS Access Management App for setting the correct access rights for various pos '
                'features like related to order, product, customer, payment etc. \n'
                '        pos cashier access rights, pos manager access,pos cashier access, pos waiter access, pos '
                'floor access, pos category access,\n'
                '        userwise pos access rights.\n'
                '    ',
 'summary': 'POS access rights on User + Employee (HR) level',
 'depends': ['point_of_sale', 'pos_hr', 'pos_sale'],
 'data': ['security/res_groups.xml',
          'security/ir.model.access.csv',
          'views/point_of_sale_access_view.xml',
          'views/pos_access_employee_view.xml',
          'views/pos_config_employee.xml',
          'views/res_config_settings_employee_views.xml'],
 'assets': {'point_of_sale._assets_pos': ['pos_access_user_employee/static/src/js/ActionPadWidget.js',
                                          'pos_access_user_employee/static/src/xml/ActionPadWidget.xml',
                                          'pos_access_user_employee/static/src/js/PaymentScreenAccessPatch.js',
                                          'pos_access_user_employee/static/src/xml/PaymentScreenAccessPatch.xml',
                                          'pos_access_user_employee/static/src/js/ProductAccessPatch.js',
                                          'pos_access_user_employee/static/src/js/TicketScreenAccessPatch.js',
                                          'pos_access_user_employee/static/src/xml/TicketScreen.xml',
                                          'pos_access_user_employee/static/src/js/PartnerListAccessPatch.js',
                                          'pos_access_user_employee/static/src/xml/PartnerListAccessPatch.xml',
                                          'pos_access_user_employee/static/src/xml/NumpadWidgetAccessPatch.xml',
                                          'pos_access_user_employee/static/src/js/NumpadWidgetAccessPatch.js',
                                          'pos_access_user_employee/static/src/js/PosActionButtonAccessPatch.js',
                                          'pos_access_user_employee/static/src/xml/PosActionButtonAccessPatch.xml',
                                          'pos_access_user_employee/static/src/js/NavbarAccessPatch.js',
                                          'pos_access_user_employee/static/src/xml/NavbarAccessPatch.xml',
                                          'pos_access_user_employee/static/src/js/DebugWidgetAccessPatch.js',
                                          'pos_access_user_employee/static/src/xml/DebugWidgetAccessPatch.xml']},
 'price': '149.00',
 'currency': 'USD',
 'installable': True,
 'application': True,
 'images': ['static/description/banner.gif'],
 'live_test_url': 'https://www.terabits.xyz/request_demo?source=index&version=18&app=simplify_pos_access_management'}